[versions]
clipboard = "2.0.8"
fileLoader = "6.2.0"
fritz2 = "0.12"
highlight = "11.2.0"
kotlin = "1.5.31"
mvp = "0.3.0"
patternFly = "4.132.2"
patternFlyFritz2 = "0.3.0-SNAPSHOT"
serialization = "1.3.0"
timeElements = "3.1.1"

[libraries]
fritz2-core = { module = "dev.fritz2:core", version.ref = "fritz2" }
fritz2-mvp = { module = "dev.fritz2:mvp", version.ref = "mvp" }
fritz2-patternfly = { module = "org.patternfly:patternfly-fritz2", version.ref = "patternFlyFritz2" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

[bundles]
fritz2 = ["fritz2-core", "fritz2-mvp", "fritz2-patternfly"]

[plugins]
js = { id = "org.jetbrains.kotlin.js", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
